use super::clock::{SequencerClock, SyncMode};
use super::pattern::Pattern;
use super::track::SequencerTrack;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Events generated by the sequencer
#[derive(Debug, Clone)]
pub enum SequencerEvent {
    /// Trigger a pad
    Trigger { pad: usize, velocity: f32 },
    
    /// Release a pad (for GATE mode)
    Release { pad: usize },
    
    /// Pattern change
    PatternChange { from: usize, to: usize },
    
    /// Step advance (for UI)
    StepAdvance { track: usize, step: usize },
}

/// Quantization modes for recording
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum QuantizeMode {
    Off,
    Quarter,
    Eighth,
    Sixteenth,
    ThirtySecond,
}

/// Main sequencer engine - polyphonic drum machine
pub struct SequencerEngine {
    /// Clock for timing
    pub clock: SequencerClock,
    
    /// Patterns (16 or more)
    pub patterns: Vec<Pattern>,
    
    /// Current pattern index
    pub current_pattern: usize,
    
    /// Queued pattern (switches on next bar)
    pub queued_pattern: Option<usize>,
    
    /// Playback state
    pub is_playing: bool,
    
    /// Recording state
    pub is_recording: bool,
    pub quantize_mode: QuantizeMode,
    
    /// Events generated this update
    events: Vec<SequencerEvent>,
    
    /// Pattern pad assignments
    /// Pad index -> Pattern to trigger
    pub pattern_assignments: HashMap<usize, usize>,
}

impl SequencerEngine {
    pub fn new() -> Self {
        let patterns = (0..16).map(Pattern::new).collect();
        
        Self {
            clock: SequencerClock::new(),
            patterns,
            current_pattern: 0,
            queued_pattern: None,
            is_playing: false,
            is_recording: false,
            quantize_mode: QuantizeMode::Sixteenth,
            events: Vec::with_capacity(32),
            pattern_assignments: HashMap::new(),
        }
    }

    /// Start playback
    pub fn play(&mut self) {
        self.is_playing = true;
        self.clock.start();
        log::info!("Sequencer started");
    }

    /// Stop playback
    pub fn stop(&mut self) {
        self.is_playing = false;
        self.clock.stop();
        
        // Reset all tracks to step 0
        for track in &mut self.patterns[self.current_pattern].tracks {
            track.reset();
        }
        
        log::info!("Sequencer stopped");
    }

    /// Toggle play/stop
    pub fn toggle_playback(&mut self) {
        if self.is_playing {
            self.stop();
        } else {
            self.play();
        }
    }

    /// Reset all tracks to step 0 without stopping playback
    pub fn reset_position(&mut self) {
        self.clock.reset();
        for track in &mut self.patterns[self.current_pattern].tracks {
            track.reset();
        }
        log::info!("Sequencer position reset to 0");
    }

    /// Update sequencer - call every frame
    pub fn update(&mut self) -> &[SequencerEvent] {
        // Update tap tempo flash
        self.clock.update_tap_flash(std::time::Duration::from_millis(16));
        
        self.events.clear();
        
        if !self.is_playing {
            return &self.events;
        }

        // Update clock and get ticks
        let ticks = self.clock.update();
        
        if ticks == 0 {
            return &self.events;
        }

        let pattern = &mut self.patterns[self.current_pattern];
        let ticks_per_step = 96 / 4; // 24 ticks per 16th note (4 steps per beat)
        
        // Check for pattern change on bar boundary first
        let (_bar, beat, tick) = self.clock.position();
        if beat == 0 && tick == 0 {
            if let Some(queued) = self.queued_pattern.take() {
                if queued != self.current_pattern {
                    // Drop pattern borrow before switching
                    let _ = pattern;
                    self.switch_pattern(queued);
                    return &self.events;
                }
            }
        }
        
        // Get current global tick for gate timing
        let current_tick = self.clock.ticks();
        
        // First, check for gate releases on all tracks
        for track_idx in 0..16 {
            let track = &mut pattern.tracks[track_idx];
            if track.update_gates(current_tick) {
                self.events.push(SequencerEvent::Release { pad: track_idx });
            }
        }
        
        // Accumulate ticks for each track and advance steps when enough ticks accumulated
        for track_idx in 0..16 {
            let track = &mut pattern.tracks[track_idx];
            
            // Accumulate ticks for this track
            track.tick_accumulator += ticks;
            
            // Check if we should advance steps
            while track.tick_accumulator >= ticks_per_step {
                track.tick_accumulator -= ticks_per_step;
                
                // Apply swing to even steps (steps 1, 3, 5, etc. are the "swung" steps)
                // For now, swing is handled by the clock - we just advance here
                
                // Advance to next step
                let prev_step = track.current_step;
                let _wrapped = track.advance();
                
                // Emit step advance event
                self.events.push(SequencerEvent::StepAdvance {
                    track: track_idx,
                    step: track.current_step,
                });
                
                // Check if we should trigger on this step
                let should_trigger = track.should_trigger();
                let current_step_idx = track.current_step;
                
                if should_trigger {
                    // Get step data before mutable borrow
                    let (velocity, ratchet, gate_length) = {
                        let step = &track.steps[current_step_idx];
                        (step.velocity, step.ratchet, step.gate_length)
                    };
                    
                    // Calculate gate length in ticks
                    let gate_length_ticks = (ticks_per_step as f32 * gate_length) as u32;
                    let gate_length_ticks = gate_length_ticks.max(1); // At least 1 tick
                    
                    // Add gate for automatic release
                    track.add_gate(current_tick, gate_length_ticks);
                    
                    // Handle ratcheting
                    for _ in 0..ratchet.max(1) {
                        self.events.push(SequencerEvent::Trigger {
                            pad: track_idx,
                            velocity,
                        });
                    }
                }
                
                // Safety check: prevent infinite loop if something goes wrong
                if track.current_step == prev_step {
                    break;
                }
            }
        }

        &self.events
    }

    /// Switch to a different pattern
    pub fn switch_pattern(&mut self, index: usize) {
        if index >= self.patterns.len() {
            return;
        }
        
        let old_pattern = self.current_pattern;
        
        // Reset old pattern
        for track in &mut self.patterns[old_pattern].tracks {
            track.is_playing = false;
        }
        
        // Switch to new
        self.current_pattern = index;
        
        // Initialize new pattern
        for track in &mut self.patterns[self.current_pattern].tracks {
            track.reset();
            track.is_playing = true;
        }
        
        self.events.push(SequencerEvent::PatternChange {
            from: old_pattern,
            to: index,
        });
        
        log::info!("Switched to pattern {}", index + 1);
    }

    /// Queue a pattern change (switches on next bar)
    pub fn queue_pattern(&mut self, index: usize) {
        if index < self.patterns.len() {
            self.queued_pattern = Some(index);
        }
    }

    /// Previous pattern
    pub fn prev_pattern(&mut self) {
        let new_index = if self.current_pattern == 0 {
            self.patterns.len() - 1
        } else {
            self.current_pattern - 1
        };
        self.queue_pattern(new_index);
    }

    /// Next pattern
    pub fn next_pattern(&mut self) {
        let new_index = (self.current_pattern + 1) % self.patterns.len();
        self.queue_pattern(new_index);
    }

    /// Get current pattern
    pub fn current_pattern(&self) -> &Pattern {
        &self.patterns[self.current_pattern]
    }

    /// Get mutable current pattern
    pub fn current_pattern_mut(&mut self) -> &mut Pattern {
        &mut self.patterns[self.current_pattern]
    }

    /// Get current track for a pad
    pub fn get_track(&self, pad: usize) -> Option<&SequencerTrack> {
        self.patterns[self.current_pattern].get_track(pad)
    }

    /// Get mutable track
    pub fn get_track_mut(&mut self, pad: usize) -> Option<&mut SequencerTrack> {
        self.patterns[self.current_pattern].get_track_mut(pad)
    }

    /// Record a pad trigger (for live recording)
    pub fn record_trigger(&mut self, pad: usize, _velocity: f32) {
        if !self.is_recording || !self.is_playing {
            return;
        }

        // Find current step based on quantize mode
        let step = self.quantized_step();
        
        if let Some(track) = self.get_track_mut(pad) {
            if let Some(s) = track.steps.get_mut(step) {
                s.active = true;
            }
        }
    }

    /// Calculate quantized step for recording
    fn quantized_step(&self) -> usize {
        let ticks_per_beat = 96u64;
        
        let steps_per_beat = match self.quantize_mode {
            QuantizeMode::Off => return 0, // No quantization
            QuantizeMode::Quarter => 1,
            QuantizeMode::Eighth => 2,
            QuantizeMode::Sixteenth => 4,
            QuantizeMode::ThirtySecond => 8,
        };
        
        let ticks_per_step = ticks_per_beat / steps_per_beat;
        let current_tick = self.clock.ticks();
        let step = (current_tick / ticks_per_step) as usize;
        
        step % self.current_pattern().length()
    }

    /// Convert step to tick
    fn step_to_tick(step: usize, _length: usize) -> u64 {
        let ticks_per_step = 96 / 4; // 16th notes
        step as u64 * ticks_per_step as u64
    }

    /// Assign a pad to trigger a pattern
    pub fn assign_pattern_pad(&mut self, pad: usize, pattern: usize) {
        if pattern < self.patterns.len() {
            self.pattern_assignments.insert(pad, pattern);
        }
    }

    /// Trigger a pattern pad
    pub fn trigger_pattern_pad(&mut self, pad: usize) {
        if let Some(&pattern) = self.pattern_assignments.get(&pad) {
            self.queue_pattern(pattern);
        }
    }

    /// Set BPM
    pub fn set_bpm(&mut self, bpm: f32) {
        self.clock.set_bpm(bpm);
    }

    /// Get BPM
    pub fn bpm(&self) -> f32 {
        self.clock.bpm()
    }

    /// Set swing
    pub fn set_swing(&mut self, swing: f32) {
        self.clock.set_swing(swing);
    }

    /// Get current position string (for display)
    pub fn position_display(&self) -> String {
        let (bar, beat, tick) = self.clock.position();
        format!("{:02}:{:02}:{:02}", bar + 1, beat + 1, tick)
    }
    
    /// Check if sequencer is playing
    pub fn is_playing(&self) -> bool {
        self.is_playing
    }
    
    /// Check if sequencer is recording
    pub fn is_recording(&self) -> bool {
        self.is_recording
    }
    
    /// Get current step for display (simplified - returns first track's step)
    pub fn current_step(&self) -> usize {
        if let Some(track) = self.patterns[self.current_pattern].tracks.first() {
            track.current_step
        } else {
            0
        }
    }
    
    /// Get all tracks from current pattern (for preset save/load)
    pub fn tracks(&self) -> &[SequencerTrack] {
        &self.patterns[self.current_pattern].tracks
    }
    
    /// Get mutable tracks from current pattern (for preset save/load)
    pub fn tracks_mut(&mut self) -> &mut [SequencerTrack] {
        &mut self.patterns[self.current_pattern].tracks
    }
    
    /// Toggle step active state
    pub fn toggle_step(&mut self, track: usize, step: usize) {
        if track < 16 && step < 64 {
            let track = &mut self.patterns[self.current_pattern].tracks[track];
            if let Some(s) = track.steps.get_mut(step) {
                s.toggle();
            }
        }
    }
    
    /// Set step active state
    pub fn set_step(&mut self, track: usize, step: usize, active: bool) {
        if let Some(t) = self.patterns[self.current_pattern].tracks.get_mut(track) {
            if let Some(s) = t.steps.get_mut(step) {
                s.active = active;
            }
        }
    }
    
    /// Set step velocity
    pub fn set_step_velocity(&mut self, track: usize, step: usize, velocity: f32) {
        if let Some(t) = self.patterns[self.current_pattern].tracks.get_mut(track) {
            if let Some(s) = t.steps.get_mut(step) {
                s.velocity = velocity.clamp(0.0, 1.0);
            }
        }
    }
    
    /// Mute a track
    pub fn mute_track(&mut self, track: usize) {
        if let Some(t) = self.patterns[self.current_pattern].tracks.get_mut(track) {
            t.muted = true;
        }
    }
    
    /// Unmute a track
    pub fn unmute_track(&mut self, track: usize) {
        if let Some(t) = self.patterns[self.current_pattern].tracks.get_mut(track) {
            t.muted = false;
        }
    }
    
    /// Tap tempo - returns new BPM after 4 taps
    pub fn tap_tempo(&mut self) -> Option<f32> {
        self.clock.tap()
    }
    
    /// Get tap tempo flash value for UI
    pub fn tap_flash(&self) -> f32 {
        self.clock.tap_flash()
    }
    
    /// Get number of taps recorded
    pub fn tap_count(&self) -> usize {
        self.clock.tap_count()
    }
    
}

impl Default for SequencerEngine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sequencer_new() {
        let seq = SequencerEngine::new();
        assert_eq!(seq.patterns.len(), 16);
        assert_eq!(seq.current_pattern, 0);
        assert!(!seq.is_playing);
        assert_eq!(seq.bpm(), 120.0);
    }

    #[test]
    fn test_toggle_step() {
        let mut seq = SequencerEngine::new();
        
        // Initially step should be inactive
        assert!(!seq.patterns[0].tracks[0].steps[0].active);
        
        // Toggle step on
        seq.toggle_step(0, 0);
        assert!(seq.patterns[0].tracks[0].steps[0].active);
        
        // Toggle step off
        seq.toggle_step(0, 0);
        assert!(!seq.patterns[0].tracks[0].steps[0].active);
    }

    #[test]
    fn test_toggle_step_bounds() {
        let mut seq = SequencerEngine::new();
        
        // These should not panic
        seq.toggle_step(99, 0); // Invalid track
        seq.toggle_step(0, 99); // Invalid step
        seq.toggle_step(99, 99); // Both invalid
    }

    #[test]
    fn test_pattern_switch() {
        let mut seq = SequencerEngine::new();
        
        // Set up pattern 0 with an active step
        seq.toggle_step(0, 0);
        assert!(seq.patterns[0].tracks[0].steps[0].active);
        
        // Switch to pattern 1
        seq.switch_pattern(1);
        assert_eq!(seq.current_pattern, 1);
        
        // Pattern 1 should have inactive step at same position
        assert!(!seq.patterns[1].tracks[0].steps[0].active);
        
        // Toggle step in pattern 1
        seq.toggle_step(0, 0);
        assert!(seq.patterns[1].tracks[0].steps[0].active);
        
        // Pattern 0's step should still be active
        assert!(seq.patterns[0].tracks[0].steps[0].active);
    }

    #[test]
    fn test_play_stop() {
        let mut seq = SequencerEngine::new();
        
        assert!(!seq.is_playing);
        
        seq.play();
        assert!(seq.is_playing);
        
        seq.stop();
        assert!(!seq.is_playing);
        
        seq.toggle_playback();
        assert!(seq.is_playing);
        
        seq.toggle_playback();
        assert!(!seq.is_playing);
    }

    #[test]
    fn test_mute_unmute_track() {
        let mut seq = SequencerEngine::new();
        
        // Initially not muted
        assert!(!seq.patterns[0].tracks[0].muted);
        
        // Mute track
        seq.mute_track(0);
        assert!(seq.patterns[0].tracks[0].muted);
        
        // Unmute track
        seq.unmute_track(0);
        assert!(!seq.patterns[0].tracks[0].muted);
    }

    #[test]
    fn test_pattern_clear() {
        let mut seq = SequencerEngine::new();
        
        // Add some steps
        seq.toggle_step(0, 0);
        seq.toggle_step(0, 4);
        seq.toggle_step(0, 8);
        
        assert!(seq.patterns[0].tracks[0].steps[0].active);
        assert!(seq.patterns[0].tracks[0].steps[4].active);
        assert!(seq.patterns[0].tracks[0].steps[8].active);
        
        // Clear pattern
        seq.current_pattern_mut().clear();
        
        assert!(!seq.patterns[0].tracks[0].steps[0].active);
        assert!(!seq.patterns[0].tracks[0].steps[4].active);
        assert!(!seq.patterns[0].tracks[0].steps[8].active);
    }

    #[test]
    fn test_bpm() {
        let mut seq = SequencerEngine::new();
        
        assert_eq!(seq.bpm(), 120.0);
        
        seq.set_bpm(140.0);
        assert_eq!(seq.bpm(), 140.0);
        
        // Test clamping
        seq.set_bpm(10.0);
        assert_eq!(seq.bpm(), 20.0);
        
        seq.set_bpm(1000.0);
        assert_eq!(seq.bpm(), 999.0);
    }

    #[test]
    fn test_track_tick_accumulator() {
        let mut track = SequencerTrack::new(0);
        assert_eq!(track.tick_accumulator, 0);
        
        // Simulate accumulating ticks
        track.tick_accumulator += 24;
        assert_eq!(track.tick_accumulator, 24);
        
        // Reset should clear accumulator
        track.reset();
        assert_eq!(track.tick_accumulator, 0);
        assert_eq!(track.current_step, 0);
    }

    #[test]
    fn test_step_advance_timing() {
        // Test that tracks advance correctly with tick accumulation
        let ticks_per_step = 24; // 16th notes at 96 PPQN
        let mut track = SequencerTrack::new(0);
        track.length = 16;
        
        // Initially at step 0
        assert_eq!(track.current_step, 0);
        
        // Add 24 ticks - should advance one step
        track.tick_accumulator += ticks_per_step;
        while track.tick_accumulator >= ticks_per_step {
            track.tick_accumulator -= ticks_per_step;
            track.advance();
        }
        assert_eq!(track.current_step, 1);
        
        // Add 48 ticks - should advance two steps
        track.tick_accumulator += 48;
        let mut advances = 0;
        while track.tick_accumulator >= ticks_per_step {
            track.tick_accumulator -= ticks_per_step;
            track.advance();
            advances += 1;
            if advances > 100 { break; } // Safety
        }
        assert_eq!(track.current_step, 3);
        assert_eq!(advances, 2);
    }

    #[test]
    fn test_partial_ticks_accumulation() {
        // Test that partial ticks accumulate correctly
        let ticks_per_step = 24;
        let mut track = SequencerTrack::new(0);
        track.length = 16;
        
        // Add 12 ticks (half a step) - should not advance
        track.tick_accumulator += 12;
        let prev_step = track.current_step;
        while track.tick_accumulator >= ticks_per_step {
            track.tick_accumulator -= ticks_per_step;
            track.advance();
        }
        assert_eq!(track.current_step, prev_step);
        assert_eq!(track.tick_accumulator, 12);
        
        // Add another 12 ticks - should now advance
        track.tick_accumulator += 12;
        while track.tick_accumulator >= ticks_per_step {
            track.tick_accumulator -= ticks_per_step;
            track.advance();
        }
        assert_eq!(track.current_step, 1);
        assert_eq!(track.tick_accumulator, 0);
    }
}
